# Prometheus Configuration for Cloud Monitoring (DigitalOcean)
# Optimized for monitoring both local and cloud services

global:
  scrape_interval: 30s # Reduced for efficiency
  evaluation_interval: 30s
  external_labels:
    environment: "production"
    instance: "flrts-cloud-monitoring"

rule_files:
  - "rules/*.yml"

scrape_configs:
  # Self-monitoring
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
    scrape_interval: 30s

  # Local container metrics
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
    scrape_interval: 30s

  # Container metrics
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
    scrape_interval: 30s
    metrics_path: /metrics

  # OpenProject application health check
  - job_name: "openproject"
    static_configs:
      - targets: ["openproject:80"]
    scrape_interval: 60s
    metrics_path: /health_checks/default
    scrape_timeout: 10s

  # n8n monitoring (custom webhook monitor)
  - job_name: "n8n-monitor"
    static_configs:
      - targets: ["n8n-monitor:3002"]
    scrape_interval: 60s
    metrics_path: /metrics

  # External services (if accessible)
  # Uncomment and modify these as needed for your local development services

  # Local development NLP service (if externally accessible)
  # - job_name: 'flrts-nlp-local'
  #   static_configs:
  #     - targets: ['YOUR_LOCAL_IP:3001']  # Replace with actual IP
  #   scrape_interval: 60s
  #   metrics_path: /metrics
  #   scrape_timeout: 15s

  # Local n8n instance (if externally accessible)
  # - job_name: 'n8n-local'
  #   static_configs:
  #     - targets: ['YOUR_LOCAL_IP:5678']  # Replace with actual IP
  #   scrape_interval: 60s
  #   metrics_path: /metrics
  #   scrape_timeout: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []
          # Add alertmanager if needed later

# Storage configuration
storage:
  tsdb:
    retention.time: 15d
    retention.size: 2GB # Limit storage usage
