# Prometheus Configuration for FLRTS Story 1.7 Monitoring
global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alertmanager configuration (optional)
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Node Exporter for system metrics
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
    scrape_interval: 30s
    metrics_path: /metrics

  # cAdvisor for container metrics
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
    scrape_interval: 30s
    metrics_path: /metrics

  # FLRTS NLP Service (OpenTelemetry metrics)
  - job_name: "nlp-service"
    static_configs:
      - targets: ["host.docker.internal:3001"]
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s

  # n8n Webhook Monitor
  - job_name: "n8n-monitor"
    static_configs:
      - targets: ["n8n-monitor:3002"]
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s

  # n8n Instance (if metrics are exposed)
  - job_name: "n8n"
    static_configs:
      - targets: ["host.docker.internal:5678"]
    scrape_interval: 30s
    metrics_path: /metrics
    scrape_timeout: 10s
    # Only scrape if n8n exposes metrics endpoint

  # Grafana self-monitoring
  - job_name: "grafana"
    static_configs:
      - targets: ["grafana:3000"]
    scrape_interval: 30s
    metrics_path: /metrics

  # Jaeger metrics
  - job_name: "jaeger"
    static_configs:
      - targets: ["jaeger:14269"]
    scrape_interval: 30s
    metrics_path: /metrics

  # PostgreSQL metrics (if pg_exporter is configured)
  # - job_name: 'postgres'
  #   static_configs:
  #     - targets: ['postgres-exporter:9187']
  #   scrape_interval: 30s
  #   metrics_path: /metrics

  # OpenTelemetry Collector metrics (if used)
  # - job_name: 'otel-collector'
  #   static_configs:
  #     - targets: ['otel-collector:8888']
  #   scrape_interval: 15s
  #   metrics_path: /metrics
