global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files: []

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
    scrape_interval: 30s
    metrics_path: /metrics

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
    scrape_interval: 30s
    metrics_path: /metrics

  - job_name: "n8n-monitor"
    static_configs:
      - targets: ["n8n-monitor:3002"]
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s

  - job_name: "grafana"
    static_configs:
      - targets: ["grafana:3000"]
    scrape_interval: 30s
    metrics_path: /metrics

  - job_name: "jaeger"
    static_configs:
      - targets: ["jaeger:14269"]
    scrape_interval: 30s
    metrics_path: /metrics
