name: BMAD QA Gate

on:
  pull_request:
    branches: [ main ]

jobs:
  qa-gate:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci || npm i

      - name: Install tools (ripgrep, shellcheck)
        run: |
          sudo apt-get update
          sudo apt-get install -y ripgrep shellcheck

      - name: Install Playwright (Chromium)
        run: npx playwright install --with-deps chromium

      - name: Run BMAD QA Gate
        run: npm run qa:gate
