name: Docs Lint (Advisory)

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'docs/**'
      - '**/*.md'
      - 'audit-results/**'

jobs:
  lint-docs:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci || npm i

      - name: Markdown lint (non-blocking)
        run: npm run lint:md

